# Generated by Django 4.1.8 on 2023-04-25 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_registrationform_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistrationForm',
            new_name='Reg',
        ),
    ]
