# Generated by Django 4.1.8 on 2023-04-25 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_reg_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='date',
        ),
    ]
