# Generated by Django 4.1.8 on 2023-04-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'Позиции', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='items',
            name='photo',
            field=models.ImageField(upload_to='Items/', verbose_name='Промо товара'),
        ),
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=7, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='items',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
    ]
