# Generated by Django 4.1.8 on 2023-04-25 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_registrationform_delete_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationform',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Зарегистрированные пользователи'},
        ),
    ]
